### ISSUE TITLE
Tests failing because of jsontableschema-py  error

### ISSUE THREAD

**Issue by georgiana-b** [frictionlessdata/goodtables#101]
[_jsontableschema-py_ 0.6.2.](https://github.com/frictionlessdata/jsontableschema-py) is raising `ConstraintNotSupported: Field type 'string' does not support the unique constraint`. For more, see [the report from Travis.](https://travis-ci.org/frictionlessdata/goodtables/jobs/130825589)
@pwalsh, should we provide functionality for the `unique` constraint in Schema processor or just drop it for now and wait until _jsontableschema-py_ supports it?

**Comment by pwalsh** [comment]
@roll

**Comment by roll** [comment]
https://github.com/frictionlessdata/jsontableschema-py/pull/74

**Comment by georgiana-b** [comment]
@pwalsh  I think the fact that [jsontableschema-py](https://github.com/frictionlessdata/jsontableschema-py) raises an error is actually an improvement  not a bug since the `unique` constraint is not supported and it shouldn't act like it is. The question is how we want to deal with the fact in GoodTables.

**Comment by pwalsh** [comment]
@georgiana-b sure. the JTS lib improved leaps and bounds without GT following suit. Please make a reasonable implementation for this now, and flag for future look (in backlog).

**Comment by roll** [comment]
@pwalsh 
@georgiana-b 
Not sure current JTS behavior is acceptable - it will fail for any schema with unique constraint. It's not only related to GT. WDYT?

**Comment by roll** [comment]
@georgiana-b 
I've fixed it in `jsontableschema-0.6.3` - behavior there was just wrong. Check for `unique` constraint support could be added to some other place if you need it.

I think now tests will pass here.

**Comment by georgiana-b** [comment]
Yes. Tests [are passing now](https://travis-ci.org/frictionlessdata/goodtables) and this version is compatible with [how we handle uniqueness in the Schema processor](https://github.com/frictionlessdata/goodtables/blob/master/goodtables/processors/schema.py#L309) so there's no problem anymore.
