### ISSUE TITLE
Check data is valid according to foreignKeys descriptor

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables#17]
When validating data against a JSON Table Schema, there may be foreign keys to other files.

This will need to be implemented in a way that supports:

* Processing of a raw data source + a table schema
* Processing of a DataPackage

**Comment by rgrp** [comment]
Good point. I don't know if you plan this as near-term but I would reiterate from "client" perspective that, for our immediate purposes, we can really follow "KISS" - see the [user story](https://docs.google.com/a/okfn.org/document/d/1Rz0v091YOH6rEv-B0Dhe--x9R-Fwfgh0Zyd45jwhdwc/edit#heading=h.ujb30vjwua6o)

**Comment by rgrp** [comment]
Note just seen #8 which clarifies this is out of scope ;-)

**Comment by pwalsh** [comment]
WONTFIX for now. This will come for free when we update GoodTables to use Tabulator and related, newer tools
