### ISSUE TITLE
Good Tables gives confusing error message re: headers

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/goodtables#59]
Running

    goodtables schema --schema https://raw.githubusercontent.com/okfn/tabular-validator/master/examples/hmt/spend-publishing-schema.json  https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/214660/Wales-Office-spend-over-500-June-2011.csv 

Returns 

> There is a mismatch between the headers according to the schema, and those found in the data. The schema says the headers should be: Department family, Entity, Date, Expense type, Expense area, Supplier, Transaction number, Amount, Description, Supplier postcode, Supplier type, Contract number, Project code, Expenditure type, VAT registration number.

This is a confusing message given that only some of those listed headers are actually required [according to the schema](https://raw.githubusercontent.com/okfn/tabular-validator/master/examples/hmt/spend-publishing-schema.json).

**Comment by pwalsh** [comment]
Duplicates https://github.com/frictionlessdata/goodtables/issues/70
