### ISSUE TITLE
Data is always valid when passed schema is not valid

### ISSUE THREAD

**Issue by gvidon** [frictionlessdata/goodtables#60]
When schema is passed but can not be translated into valid JSON Table schema validator always says that data is valid.

Examples
* ```schema={}``` http://goodtables.okfnlabs.org/reports?data_url=https%3A%2F%2Fraw.githubusercontent.com%2Fokfn%2Fgoodtables-web%2Fmaster%2Fexamples%2Finvalid-on-structure.csv&format=csv&encoding=&schema_url=&schema=%7B%7D
* ```schema=123``` http://goodtables.okfnlabs.org/reports?data_url=https%3A%2F%2Fraw.githubusercontent.com%2Fokfn%2Fgoodtables-web%2Fmaster%2Fexamples%2Finvalid-on-structure.csv&format=csv&encoding=&schema_url=&schema=123

**Comment by georgiana-b** [comment]
Currently an  `InvalidSchemaError` is [being raised](https://github.com/frictionlessdata/goodtables/blob/master/tests/test_schema.py#L529) so, as I understand it, this issue has been solved.

**Comment by pwalsh** [comment]
fixed.
