### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by davidread** [frictionlessdata/goodtables#64]
http://goodtables.okfnlabs.org/reports?data_url=http://data.defra.gov.uk/ops/government_procurement_card/over_%C2%A3500_GPC_apr_2013.csv&format=CSV&encoding=&schema_url=https://raw.githubusercontent.com/okfn/tabular-validator/master/examples/hmt/spend-publishing-schema.json

**Comment by pwalsh** [comment]
@davidread thanks, something broke here.

**Comment by georgiana-b** [comment]
In theory the solution should also work in py2 but strings get deformed (eg: `over_£500_GPC_apr_2013.csv` is turned into `over_ÂŁ500_GPC_apr_2013.csv` ) when being read from the sources file for a reason I failed to discover.

**Comment by pwalsh** [comment]
Fixed
