### ISSUE TITLE
zip file recognized as html

### ISSUE THREAD

**Issue by davidread** [frictionlessdata/goodtables#65]
This is a zip file, yet Good Tables error message says it is probably HTML. Nor does the preview help. 

http://goodtables.okfnlabs.org/reports?data_url=http://webarchive.nationalarchives.gov.uk/+/https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/172821/alb-data-aug-2012.zip.zip&format=ZIP&encoding=&schema_url=https://raw.githubusercontent.com/okfn/tabular-validator/master/examples/hmt/spend-publishing-schema.json

**Comment by georgiana-b** [comment]
This data source actually returns 404 which leads to an Internal Server Error in http://goodtables.okfnlabs.org. I opened #86 instead so this can be closed.

**Comment by pwalsh** [comment]
FIXED
