### ISSUE TITLE
Fields set to constraints.required = false yield schema error when missing

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/goodtables#68]
When validating a CSV file with missing fields, I still get a validation error (Incorrect Type) even when I've set the field's constraints.required to false.

```
{
  "name": "days_to_death",
  "type": "integer",
  "constraints": {
    "required": false
  }
},
```

![screen shot 2016-02-25 at 17 23 11](https://cloud.githubusercontent.com/assets/772616/13322257/a8b7ff52-dbe4-11e5-80d6-b425d1bba21f.png)

**Comment by georgiana-b** [comment]
I can replicate this in `goodtables.io` but not in `goodtables`. My best guess is that `goodtables.io` doesn't have the latest code. Someone with credentials please upgrade the requirements for `goodtables.io` and leave a comment after doing so.

**Comment by georgiana-b** [comment]
I tried to replicate this here as well as in `goodtables.io` run locally with no success. However, the same files used for the test in frictionlessdata/goodtables.io@b3a1573  do give this error on http://goodtables.okfnlabs.org/ so my best guess is that `goodtables.okfnlabs` server doesn't have the latest code. Somebody with credentials please update it's requirements and leave a comment here after doing so.

**Comment by pwalsh** [comment]
@georgiana-b labs instance is now live using GoodTables 0.7.0 https://pypi.python.org/pypi/goodtables/0.7.0

**Comment by georgiana-b** [comment]
The same test files are now [recognized as valid on `goodtables.okfnlabs`](http://goodtables.okfnlabs.org/reports?data_url=https%3A%2F%2Fgist.githubusercontent.com%2Fgeorgiana-b%2F4f55b396b72213748b869d29c3418bd5%2Fraw%2F6faee6bf37d7c48dda381ff8e77769abda2f5ec4%2Fpersons.csv&format=csv&encoding=&schema_url=https%3A%2F%2Fgist.githubusercontent.com%2Fgeorgiana-b%2F4f55b396b72213748b869d29c3418bd5%2Fraw%2F6faee6bf37d7c48dda381ff8e77769abda2f5ec4%2Fperson_schema.json). All good.

**Comment by pwalsh** [comment]
FIXED.
