### ISSUE TITLE
Bad UX when reporting on errors in column headings

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables#70]
Has come up in various ways over last year.

Example from work with Cabinet Office at UK:

"the most common error is the wrong column headings, but the error message is not clear enough to say there is a mismatch. It seems much more helpful to clarify what's missing and what should be removed.
e.g. "Missing required column headings: 'Amount', 'Department family'. Column name not allowed: 'Internal code’"."

cc @davidread

**Comment by davidread** [comment]
Yup!
